 version: 2.1
  jobs:
    build:
     working_directory: ~/fetch-http-utils
      docker: 
        - image: circleci/node:10.16.3 # the primary container, where your job's commands are run
      steps:
        - checkout
        - run:
            name: update-npm
            command: 'sudo npm install -g npm@latest'
        - restore_cache:
            key: dependency-cache-{{ checksum "package-lock.json" }}
        - run:
            name: install-npm-wee
            command: npm install
        - save_cache:
            key: dependency-cache-{{ checksum "package-lock.json" }}
            paths:
              - ./node_modules